<script lang="ts">

    // --- Components ---
    import { Frame } from "@lib/ui"

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className = $bindable(undefined),
        ...rest
    }: Props = $props();

</script>

<Frame class={ cn(className) } {...rest} flex>
    {@render children?.()}
</Frame>

<!--@component
    Generated by SvelteForge🔥

    # Flex Component
    Wrapper component for Frame with the flex attribute passed
-->

