<script lang="ts">
	// --- Logic ---
	import { cn, uuidv4 } from '@lib/utils';
	import type { Props } from '..';

	let {
		children,

		// Classes
		classFrame,
		class: className,
		classLabel,

		// Properties
		type,
		name,
		id = undefined,

		// Frame Passdown
		flex,
		row,
		col,
		center,
		centerx,
		centery,
		fill,
		fillw,
		fillh,
		noshrink,
		aspectSquare,
		cursorAuto,
		cursorDefault,
		cursorPointer,

		...rest
	}: Props = $props();

	// Set id if not specified
	if (!id) {
		id = uuidv4();
	}
</script>

<Frame
	{flex}
	{row}
	{col}
	{center}
	{centerx}
	{centery}
	{fill}
	{fillw}
	{fillh}
	{noshrink}
	{aspectSquare}
	{cursorAuto}
	{cursorDefault}
	{cursorPointer}
	class={cn(classFrame)}
>
	<input class={cn(className)} {type} {name} {id} {...rest} />

	{#if children}
		<label for={id} class={cn(classLabel)}>{@render children?.()}</label>
	{/if}
</Frame>

<!--@component
    Generated by SvelteForge🔥

    # Input Component
    Wrapper for input element that renders children within a label tag
-->
