<script lang="ts">
	// --- Logic ---
	import { cn, uuidv4 } from '@lib/utils';
	import type { Props } from '..';

	let {
		children,

		// Classes
		class: className,
		classLabel,

		// Properties
		type,
		name,
		id = undefined,

		// Catchall
		...rest
	}: Props = $props();

	// Set id if not specified
	if (!id) {
		id = uuidv4();
	}

	// Setup Input's class
	let inputCls = $state(cn(inputClass, className));
	$effect(() => {
		inputCls = cn(inputClass, className);
	});
</script>

<input class={cn(className)} {type} {name} {id} {...rest} />

{#if children}
	<label for={id} class={cn(classLabel)}>{@render children?.()}</label>
{/if}

<!--@component
    Generated by SvelteForge🔥

    # Input Component
    Wrapper for input element that renders children within a label tag
-->
