<script lang="ts">
	// --- Logic ---
	import { cn, uuidv4 } from '@lib/utils';
	import type { Props } from '..';
	import { Frame } from '@lib/ui';

	let {
		children,

		// Classes
		classFrame,
		class: className,
		classLabel,

		// Properties
		type = $bindable(undefined),
		name = $bindable(undefined),
		id = $bindable(undefined),

		// Frame Passdown
		flex = $bindable(undefined),
		row = $bindable(undefined),
		col = $bindable(undefined),
		center = $bindable(undefined),
		centerx = $bindable(undefined),
		centery = $bindable(undefined),
		fill = $bindable(undefined),
		fillw = $bindable(undefined),
		fillh = $bindable(undefined),
		noshrink = $bindable(undefined),
		aspectSquare = $bindable(undefined),
		cursorAuto = $bindable(undefined),
		cursorDefault = $bindable(undefined),
		cursorPointer = $bindable(undefined),

		...rest
	}: Props = $props();

	// Set id if not specified
	if (!id) {
		id = uuidv4();
	}
</script>

<Frame
	{flex}
	{row}
	{col}
	{center}
	{centerx}
	{centery}
	{fill}
	{fillw}
	{fillh}
	{noshrink}
	{aspectSquare}
	{cursorAuto}
	{cursorDefault}
	{cursorPointer}
	class={cn(classFrame)}
>
	<input class={cn(className)} {type} {name} {id} {...rest} />

	{#if children}
		<label for={id} class={cn(classLabel)}>{@render children?.()}</label>
	{/if}
</Frame>

<!--@component
    Generated by SvelteForge🔥

    # Input Component
    Wrapper for input element that renders children within a label tag
-->
