<script lang="ts">
	// --- Logic ---
	import { cn, Tokenizer } from '@lib/utils';
	import { type Props } from '..';

	// Size Class Lookup Table
	const sizeClasses = {
		xxl: 'text-2xl',
		xl: 'text-xl',
		lg: 'text-lg',
		md: 'text-base',
		sm: 'text-sm'
	};

	// Semantic Sizes Lookup Table
	const semanticSizes = {
		xxl: 'h1',
		xl: 'h2',
		lg: 'h3',
		md: 'h4',
		sm: 'h5'
	};

	// Weight Classes Lookup Table
	const weightClasses = {
		extrabold: 'font-extrabold',
		bold: 'font-bold',
		semibold: 'font-semibold',
		regular: 'font-normal',
		light: 'font-light'
	};

	let {
		children,
		class: className = $bindable(undefined),

		// Sizing
		size = 'md', // Catch All
		xxl,
		xl,
		lg,
		md,
		sm,

		// Weights
		weight = 'regular', // Catch All
		extrabold,
		bold,
		semibold,
		regular,
		light,

		// Semantic Element
		as = undefined, // Catchall

		// Italics
		em,

		...rest
	}: Props = $props();

	const tokenInstance = new Tokenizer(className);

	// === Catch All statements should be applied first ===

	// Apply Size Class
	tokenInstance.addTokenIf(true, sizeClasses[size] ?? 'text-base');

	// Apply Weight Class
	tokenInstance.addTokenIf(true, weightClasses[weight] ?? 'font-normal');

	// Sizing Tokens
	tokenInstance.addTokenIf(xxl, 'text-2xl');
	tokenInstance.addTokenIf(xl, 'text-xl');
	tokenInstance.addTokenIf(lg, 'text-lg');
	tokenInstance.addTokenIf(md, 'text-base');
	tokenInstance.addTokenIf(sm, 'text-sm');

	function determineSemanticViaSize() {
		// Go in order of importance, top-down
		if (xxl) return 'h1';
		if (xl) return 'h2';
		if (lg) return 'h3';
		if (md) return 'h4';
		if (sm) return 'h5';

		// Fallback to size prop
		return semanticSizes[size] ?? 'span';
	}

	// Weight Tokens
	tokenInstance.addTokenIf(extrabold, 'font-extrabold');
	tokenInstance.addTokenIf(bold, 'font-bold');
	tokenInstance.addTokenIf(semibold, 'font-semibold');
	tokenInstance.addTokenIf(regular, 'font-normal');
	tokenInstance.addTokenIf(light, 'font-light');

	// Italic Token
	tokenInstance.addTokenIf(em, 'italic');

	// Determine Semantic Tag
	let semanticTag = as ?? determineSemanticViaSize();
</script>

<svelte:element this={semanticTag} class={cn(tokenInstance.className)} {...rest}>
	{@render children?.()}
</svelte:element>

<!--@component
	Generated by SvelteForge🔥

	# Header Component
	A semantic and styled heading component that combines typography flexibility with accessible HTML.

	This component maps `size` values to both Tailwind classes and semantic tags (`h1`–`h5`),
	while also allowing direct override with the `as` prop for full control.

	## Props

	- `size`: `"xxl" | "xl" | "lg" | "md" | "sm"` — sets both font size and default semantic tag.
	- `as`: `"h1" | "h2" | "h3" | "h4" | "h5" | "span"` — override the default semantic tag.
	- `weight`: `"extrabold" | "bold" | "semibold" | "regular" | "light"` — font-weight control.
	- `xxl`, `xl`, `lg`, `md`, `sm`: boolean shorthands to set font size via token (overrides `size`).
	- `extrabold`, `bold`, `semibold`, `regular`, `light`: boolean shorthands to set weight (overrides `weight`).
	- `em`: boolean — italicizes the text.
	- `class`: Tailwind utility classes to append additional styling.
	- `children`: Rendered content of the header.

	## Example

	```svelte
	<Header size="xl" weight="semibold">
		Dashboard
	</Header>

	<Header lg bold em>
		Welcome Back!
	</Header>

	<Header size="md" as="h2">
		Settings
	</Header>
	```

	Defaults to a `h4` tag (`md` size) with `regular` weight if not specified.
-->

