<script lang="ts">

    // --- Logic ---
    import { cn, Tokenizer } from '@lib/utils';
    import type { Props } from ".."

    // Size Class Lookup Table
	const sizeClasses = {
		xxl: 'text-lg',
		xl: 'text-base',
		lg: 'text-sm',
		md: 'text-xs',
		sm: 'text-xxs'
	};
    
    // Weight Classes Lookup Table
	const weightClasses = {
		extrabold: 'font-extrabold',
		bold: 'font-bold',
		semibold: 'font-semibold',
		regular: 'font-normal',
		light: 'font-light'
	};
    
    let {
        children,
        class: className,

        // Sizing
		size = 'md', // Catch All
		xxl,
		xl,
		lg,
		md,
		sm,

        // Weights
		weight = 'regular', // Catch All
		extrabold,
		bold,
		semibold,
		regular,
		light,

        // Semantic Element
		as = "span", // Catchall

        // Italics
		em,

        // Other Catchall
        ...rest
    }: Props = $props();

    const tokenInstance = new Tokenizer(className);

    // === Catch All statements should be applied first ===

    // Apply Size Class
    tokenInstance.addTokenIf(true, sizeClasses[size] ?? 'text-base');

    // Apply Weight Class
    tokenInstance.addTokenIf(true, weightClasses[weight] ?? 'font-normal');

    // Sizing Tokens
    tokenInstance.addTokenIf(xxl, sizeClasses['xxl']);
    tokenInstance.addTokenIf(xl, sizeClasses['xl']);
    tokenInstance.addTokenIf(lg, sizeClasses['lg']);
    tokenInstance.addTokenIf(md, sizeClasses['md']);
    tokenInstance.addTokenIf(sm, sizeClasses['sm']);

    // Weight Tokens
    tokenInstance.addTokenIf(extrabold, weightClasses['extrabold']);
    tokenInstance.addTokenIf(bold, weightClasses['bold']);
    tokenInstance.addTokenIf(semibold, weightClasses['semibold']);
    tokenInstance.addTokenIf(regular, weightClasses['regular']);
    tokenInstance.addTokenIf(light, weightClasses['light']);

    // Italic Token
    tokenInstance.addTokenIf(em, 'italic')
</script>

<svelte:element this={as} class={cn(tokenInstance.className)} {...rest}>
	{@render children?.()}
</svelte:element>

<!--@component
    Generated by SvelteForge🔥
-->

