<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';

	let { children, class: className, buttonClass = $bindable('px-4 py-2 rounded-md bg-[var(--color-primary)] color-[var(--color-white)]'), ...rest }: Props = $props();

	// Setup Button's Default Class
	let buttonCls = $state(cn(buttonClass, className));
	$effect(() => {
		buttonCls = cn(buttonClass, className);
	});
</script>

<button class={cn(buttonCls)} {...rest} tabindex="0">
	{@render children?.()}
</button>

<!--@component
    Generated by SvelteForge🔥

    # Button Component
    Simple button component for easy customization and easy onclick functionality
-->
