<script lang="ts">
	// --- Logic ---
	import { cn } from '@lib/utils';
	import type { Props } from '..';

	let { children, class: className, ...rest }: Props = $props();
</script>

<button class={cn(className)} {...rest}>
	{@render children?.()}
</button>

<!--@component
    Generated by SvelteForge🔥
-->
