name: Deploy to Github Pages

on:
  push:
    paths:
        - 'packages/site/**'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/
          cache-dependency-path: packages/site/package-lock.json
      
      - name: Clean Install Dependencies
        working-directory: packages/site
        run: |
          rm -rf node_modules package-lock.json
          npm install --force

      - name: Build
        working-directory: packages/site
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'  # Set BASE_PATH dynamically
        run: npm run webbuild

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'packages/site/build'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
