<script lang="ts">
	// --- Logic ---
	import { cn, Tokenizer } from '@lib/utils';
	import type { Props } from '..';

	let { children, class: className, headerClass = $bindable('') }: Props = $props();

	// Sizes
	/**
	 * sm
	 * md => Default
	 * lg
	 * xl
	 * xxl
	 */

	// Weights
	/**
	 * light
	 * regular => Default
	 * semibold
	 * bold
	 * extrabold
	 */

	// Types
	/**
	 * em
	*/
    
	// Setup Header's class
	let headerCls = $state(cn(headerClass, className));
	$effect(() => {
		headerCls = cn(headerClass, className);
	});
</script>

<div class={headerCls}>
	{@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->
